### ISSUE TITLE
Upgrade to the newest Key Vault implementation since key vault flexvol is deprecated

### ISSUE THREAD

**Issue by knunery** [mspnp/microservices-reference-implementation#177] opened 2020-06-02 21:03 UTC
The deployment step "[Setup AAD pod identity and key vault flexvol infrastructure](https://github.com/mspnp/microservices-reference-implementation/blob/master/deployment.md#setup-aad-pod-identity-and-key-vault-flexvol-infrastructure)" uses the deprecated version of a key vault implementation. The reference sample should be upgraded to use "[Azure Key Vault Provider for Secrets Store CSI Driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure)".

**Comment by ferantivero** [comment] 2020-07-07 21:43
thanks for sharing this information @knunery, we've started to experiment with the Azure KeyVault Provider for Secrets Store CSI from another Reference Implementation. Please let us keep this open for a while so we could share the link to the new repo when it gets published. 

On the other hand, we might incorporate such integration to this repo in the future. This is not confirmed thought.

Please stay tuned.

cc/ @doodlemania2

**Comment by ferantivero** [comment] 2020-07-20 15:17
@knunery in the meantime please let us share our new [AKS Secure Baseline repo](https://github.com/mspnp/aks-secure-baseline) where you can find the integration with  [Azure Key Vault Provider for Secrets Store CSI Driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure)

**Comment by nitinkhandelwal26** [comment] 2020-08-11 17:53
@ferantivero since this is deprecated, can this reference implementation upgraded to latest Azure Key Vault Provider for Secrets Store CSI driver?

**Comment by magrande** [comment] 2021-06-04 15:20
Upgraded to latest Azure Key Vault Provider for Secrets Store CSI driver, in this PR:

https://github.com/mspnp/microservices-reference-implementation/pull/216\

Closing this issue. Thanks !

**Closed by magrande** 2021-06-04 15:20 UTC
